services:
  - type: web
    name: tehrimap
    env: docker
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /
    healthCheckTimeout: 100
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MONGODB_URI
        sync: false # Will be set manually in Render dashboard
      - key: JWT_SECRET
        sync: false # Will be set manually in Render dashboard
      - key: PORT
        value: 8080
    buildCommand: |
      chmod +x ./mvnw
      ./mvnw clean package -DskipTests
    dockerfilePath: ./Dockerfile
    startCommand: "java -Xmx512m -jar app.jar" 